name: CI to Docker hub for main G3W-SUITE image.

on:
  push:
    branches:
      - v3.0.x

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Extract branch name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.g3wsuite.dockerfile
          push: true
          tags: g3wsuite/g3w-suite:${{ env.BRANCH_NAME }}

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
