name: CI to Docker hub for dependencies image.

on:
  push:
    branches: [ dev ]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.g3wsuite-deps.ltr.dockerfile
          push: true
          tags: g3wsuite/g3w-suite-deps-ltr:3.10.x

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
